name: pokemon
description: pokemon game

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  dio: ">=4.0.6 <6.0.0"
  dartz: ^0.10.1
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0
  auto_route: ^4.0.1
  internet_connection_checker: ^0.0.1+3
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  build_runner:

flutter:
  uses-material-design: true
